### ISSUE TITLE
Merge devel, update submodule

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xorgxrdp#10]
How would you like to merge devel into master and update xorgxrdp submodule in xrdp repository?

The main differences between devel and master are f745376610d9aac769877401f84f9fe5c7293e83  and a7de845e3a6746b350ecbb9c139fb5514baeffce. I believe these are convenient for most users.

**Comment by jsorg71** [comment]
Done

**Comment by metalefty** [comment]
Thanks!
