### ISSUE TITLE
Verify PGP key

### ISSUE THREAD

**Issue by Chocobo1** [neutrinolabs/xorgxrdp#112]
Well this is not an actual issue about the program...
I've noticed that this project also provide PGP signatures (the .asc file) for releases, however I cannot easily verify the public key (which I obtained from keyserver) belongs to the maintainer (I got `Koichiro IWAO <meta@vmeta.jp>` and I can only **guess** it is @metalefty).
So I'm asking if you can make/declare your public key more visible, either a news post on the main website or just include it in the repository.

Thank you very much.

**Comment by metalefty** [comment]
That makes sense. I should learn how other projects does.

**Comment by metalefty** [comment]
Now my key can be found here: https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.2.8

I'm going to up include it in the repository later.

**Comment by mantinan** [comment]
Looks like this is an issue again, current 0.9.13.1 seems to be signed with 03993B4065E7193B which isn't current metalefty's key, at least not the one specified on this issue or metalefty's github's announced one.

**Comment by metalefty** [comment]
Sorry about that, it is my subkey. I accidentally signed the tarball with the subkey.

**Comment by metalefty** [comment]
Let me some time.

**Comment by mantinan** [comment]
Sorry that I wrote it here googled for xrdp and ended up on the bug for xorgxrdp, I was refering to xrdp 0.9.13.1, not xorgxrdp :-)

**Comment by metalefty** [comment]
No problem, thanks for the report.

**Comment by metalefty** [comment]
@mantinan Now you should be able to verify. See also neutrinolabs/xrdp#1627.
