### ISSUE TITLE
Buildfailure on Xorg 20 using meson

### ISSUE THREAD

**Issue by LeonardKoenig** [neutrinolabs/xorgxrdp#119]
Xorg 20 made the XvExtension optional also for meson. But even when enabling `xv=true` when building, `./include/xorg-server.h.meson.in` does only `#mesondefine XvExtension`, while the old autoconf based buildsystem did `#define XvExtension 1`, which results in an error when building:

```
Making all in xrdpdev
make[2]: Entering directory '/home/leonard/.cache/aurman/xorgxrdp/src/xorgxrdp-0.2.6/xrdpdev'
  CC       xrdpdev.lo
xrdpdev.c: In function ‘rdpScreenInit’:
xrdpdev.c:471:40: error: operator '&&' has no right operand
 #if defined(XvExtension) && XvExtension
                                        ^
make[2]: *** [Makefile:457: xrdpdev.lo] Error 1
make[2]: Leaving directory '/home/leonard/.cache/aurman/xorgxrdp/src/xorgxrdp-0.2.6/xrdpdev'
make[1]: *** [Makefile:425: all-recursive] Error 1
make[1]: Leaving directory '/home/leonard/.cache/aurman/xorgxrdp/src/xorgxrdp-0.2.6'
make: *** [Makefile:357: all] Error 2
```

Either we should only check for `XvExtension` being defined and not it's value or file a bug against upstream Xorg to restore old/compatible behavior.

**Comment by jsorg71** [comment]
Thanks for reporting, I'll take a look.  It seems 1.20 was releases May 10 2018.

**Comment by jsorg71** [comment]
This looks like a bug on their side.  There is not a good way to fix it on our side.

**Comment by LeonardKoenig** [comment]
Well, I don't know what they guaranteed per spec: defined or defined to 1. In the latter case it's a bug on their side, in the former a reliance on unspecified behavior on this side.

But even in the latter case they might want to transition to only it being defined since the value '1' has no special meaning to them. `XvExtension` is no single case but it seems that pretty much every extension is handled that way and, with meson, merely defined than defined to a specific value.

If it did have an intended meaning in earlier X versions but they don't this anymore, one could of course check against the X version

```
#if defined(XvExtension) && (/* X Version >= 1.20 || XvExtension */)
```

Since `XvExtension` will only evaluated when X Version < 1.20 this should work.

**Comment by geiseri** [comment]
@jsorg71 thoughts on the proposed fix?

**Comment by jsorg71** [comment]
checking for Xorg version does not fix it.  you need to check for meson.  It builds fine with autotools.  This is a bug in the meson config in Xorg, it's still under development the way it looks.

**Comment by LeonardKoenig** [comment]
Yes, it's impossible though to check whether the installed system was built using meson or not, however with Xorg 1.20 quite many distributors changed to meson, hence the version check.

We could also just go full-on, and kill the check for the *value* of `XvExtension* altogether, since I've not seen this *anywhere* else at all, it's probably code that just "happened to work" anyway. Or is there a specifying that such check is legal or even needed?

**Comment by jsorg71** [comment]
I think we can change it to
#if defined(XvExtension)
and get rid of the second part.
I checked with
meson configure -Dxv=false
and XvExtension is not defined in that case.

**Comment by jsorg71** [comment]
I created #122 for this

**Comment by LeonardKoenig** [comment]
@jsorg71 Yep, this should work, at least for current Xorg, but glanicing into the sources of X makes it look as this should also work for older revisions, so LG2M.
