### ISSUE TITLE
multihead bug ?

### ISSUE THREAD

**Issue by smooker** [neutrinolabs/xorgxrdp#12]
From 6fcf7a2b46dcfb0f20c40335314a9da2de34159b Mon Sep 17 00:00:00 2001
From: smooker atvservice@mail.bg
Date: Fri, 16 Sep 2016 22:53:00 +0300
Subject: [PATCH] ugly patch for multihead systems

---

 xrdpdev/xrdpdev.c | 13 ++++++++-----
 1 file changed, 8 insertions(+), 5 deletions(-)

diff --git a/xrdpdev/xrdpdev.c b/xrdpdev/xrdpdev.c
index 259f785..3ee452f 100644
--- a/xrdpdev/xrdpdev.c
+++ b/xrdpdev/xrdpdev.c
@@ -149,13 +149,16 @@ rdpPreInit(ScrnInfoPtr pScrn, int flags)
     LLOGLN(0, ("rdpPreInit:"));
     if (flags & PROBE_DETECT)
     {
-       LLOGLN(0, ("rdpPreInit1:"));
       return FALSE;
   }
-    if (pScrn->numEntities != 1)
-    {
-        return FALSE;
## \-    }

+//    if (pScrn->numEntities != 1)
+//    {
+//     LLOGLN(0, ("rdpPreInit3:"));
+//        return FALSE;
+//    }
-   
-   LLOGLN(0, ("rdpPreInit4:"));
   rdpAllocRec(pScrn);
   dev = XRDPPTR(pScrn);
## 

2.9.3

**Comment by jsorg71** [comment]
How did you trigger this condition?
Did you edit the xorg.conf file?

**Comment by smooker** [comment]
nope. 
just connected two other monitors (totally 3).
xorg 1.18
devel xrdp

**Comment by proski** [comment]
@smooker Please describe the issue so others can see if they reproduced your issue or something else. Also please use correct formatting for your patch. If you can, please rebase the patch against the current code in git.

**Comment by jsorg71** [comment]
I think this is fixed in #15
