### ISSUE TITLE
root rights when using the xorg driver

### ISSUE THREAD

**Issue by hschraep** [neutrinolabs/xorgxrdp#126]
Hello Team,
i can successfull start a xrdp session over xorgxrdp. But i musst in this session type in so many authorisations for root. It beginns after the login, i have to authentication 3 times some things that needs the root authentication. If i would start a KVM i have to do this 16 times. If i login with the same user directly at the PC i have to do this not.
The OS is:
NAME="Red Hat Enterprise Linux Workstation"
VERSION="7.5 (Maipo)"

Installed xrdp versions:
$ rpm -qa |grep xrdp
xorgxrdp-0.2.7-1.el7.x86_64
xrdp-0.9.7-1.el7.x86_64

Xrdp conf:

xrdp.ini
[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20

sesman.ini
param=Xorg
; Leave the rest paramaters as-is unless you understand what will happen.
param=-config
param=xrdp/xorg.conf
param=-noreset
param=-nolisten
param=tcp
param=-logfile
param=.xorgxrdp.%s.log

Can you give me a tip what i have to setup that i have to do this not? If you need some more logs let me know which one.

**Comment by metalefty** [comment]
Are you talking about "Authentication is required to create a color managed device"  dialog?

**Comment by hschraep** [comment]
right this is the messesage for i need to type in the root password. At the log in i have to do it 3 times one of it is for the color management.

**Comment by metalefty** [comment]
Then, it is out of our scope. The same issue occurs also VNC or x2go as well. Google it.

https://github.com/TurboVNC/turbovnc/issues/47
https://bugzilla.redhat.com/show_bug.cgi?id=1149893

**Comment by hschraep** [comment]
I do not understand why this problem do not occure if im local at the PC. Then i could use it normaly. For me it looks like xorgxrdp willl not start with the right rights. If i use vnc and start it with port=:0 i have not this problems. But i would not use VNC because the PC to where i will connect have a smaler resolution as my monitor have from where i connect. So xorgxrdp is the right for me but with this restrictions. I have tryed to set the port settings with xorgxrdp also to :0 but this will not work. It looks for me with the port=-1 settings that it will open a new xorg session that is not the same that is on the local machine. With port setting port=:0 the screens are the same but only under VNC. So can you say what is here the driffrens?

**Comment by metalefty** [comment]
Don' be misled by traditonal unix root / reguler user permissions. It is controlled by polkit.
Anyway, not the xorgxrdp issue.

**Comment by hschraep** [comment]
Ok but is it possible to have the same screen with xorgxrdp like with xrdp and vnc? I mean that the screen on the PC where xrdp is running is the same on the PC from where i start the sesion to the xrdp server. So this could be the solution for me. Right now it is so that the screen with xorgxrdp and the config is set to port=-1 is diffrent as in vnc if the port is set to port=:0 .

**Comment by metalefty** [comment]
> So this could be the solution for me. 

Right. But not the only solution. Why not give permission to colord via polkit?

**Comment by hschraep** [comment]
This solves only this problem with the colord permission, but this is only a little solution because i have only type in the password 3 times. If i start a KVM i have to type in the password 10  times or more this sucks more. So the colord problem is not the real problem. Also i have a program that not ask after the permission and will not run with the right permissions. So i think, the best solution where to have to run the xorgxrdp at port=:0 . But right now i cloud'nt configure it. If you have for this a solution this would be grate.
