### ISSUE TITLE
Shared session with multiple users - configuration option?

### ISSUE THREAD

**Issue by decalek** [neutrinolabs/xorgxrdp#128]
In neutrinolabs/xrdp#883 @metalefty successfully points another user to just revert *f745376 - only allow one client connection at one time* in order to solve his use case - classroom. My use case is similar - remote pair work.

Is it still safe to revert f745376 with the current version. If yes, Is it a good idea to look for ways to make this configurable?

Thanks!

**Comment by metalefty** [comment]
I believe it is still safe but test it yourself. At least I don't think to make it configurable is a bad idea but a little bit too much effort than benefit. I think people who want to share a session should revert it by themselves.

**Comment by metalefty** [comment]
You don't need to revert in git at all. Just you need to `git clone` and change the `#if 1` to `#if 0`.  Nothing's difficult.

**Comment by sereeds** [comment]
That worked great.  Thank you very much.

I initially did try making that change shown in the revision, but I figured that I was also supposed to remove that added line shown, `LLOGLN....`
So that's where I went wrong in changing the source at first.  Lesson learnt.

Thanks for the info :-)

**Comment by mailinglists35** [comment]
>At least I don't think to make it configurable is a bad idea but a little bit too much effort than benefit

@metalefty is it possible to release two versions then, one with default and one with shared session? as an end user i find it much more difficult to maintain custom builds than adding prebuilt binaries from various repos. for example 0.9.8 which fixed the unmounting of fuse shared drive is already available in epel-testing so I would not need to build from sources.
