### ISSUE TITLE
xorgxrdp graph

### ISSUE THREAD

**Issue by THLIVSQAZ** [neutrinolabs/xorgxrdp#136]
xorgxrdp only use the llvmpipe ,but my graph is AMD Raven,so the remote is very slow,is any way to change it?
thanks developer

**Comment by jsorg71** [comment]
Glamor works with AMD GPUs too.
see https://github.com/neutrinolabs/xrdp/issues/1029

**Comment by THLIVSQAZ** [comment]
Thanks,i will try it
