### ISSUE TITLE
configure --prefix is ignored

### ISSUE THREAD

**Issue by gautaz** [neutrinolabs/xorgxrdp#163]
Hello,

Issue might be PEBKAC but whatever path I pass to the `--prefix` option of `configure`, it seems to be ignored:

**/tmp/xorgxrdp # ./bootstrap**
```
/usr/bin/autoconf
/usr/bin/automake
/usr/bin/libtool
/usr/bin/pkg-config
autoreconf: Entering directory `.'
.....
```
**/tmp/xorgxrdp # ./configure --prefix=/opt/xorgxrdp**
```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
.....
```
**/tmp/xorgxrdp # make install**
```
Making install in module
make[1]: Entering directory '/tmp/xorgxrdp/module'
Making install in amd64
make[2]: Entering directory '/tmp/xorgxrdp/module/amd64'
  NASM     a8r8g8b8_to_a8b8g8r8_box_amd64_sse2.lo
....
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libxorgxrdp.la '/usr/lib/xorg/modules'
libtool: install: /usr/bin/install -c .libs/libxorgxrdp.so /usr/lib/xorg/modules/libxorgxrdp.so
libtool: install: /usr/bin/install -c .libs/libxorgxrdp.lai /usr/lib/xorg/modules/libxorgxrdp.la
libtool: install: /usr/bin/install -c .libs/libxorgxrdp.a /usr/lib/xorg/modules/libxorgxrdp.a
.....
```

Any idea why `make install` is sticking to the `/usr` install prefix?

**Comment by metalefty** [comment]
It needs to be installed to `moduledir` otherwise it might not work.

See where `moduledir` is.
```
pkg-config --variable=moduledir xorg-server
```

Set `--enable-strict-locations` to override `moduledir`.

**Comment by gautaz** [comment]
@metalefty Thanks for the tip. I did try `--enable-strict-locations` but not with a `moduledir` setting.

Perhaps this should be fixed/documented somehow?

**Comment by metalefty** [comment]
> Thanks for the tip. I did try --enable-strict-locations but not with a moduledir setting.

Maybe you meant `--enable-strict-locations` with custom `--prefix`.

> Perhaps this should be fixed/documented somehow?

I do not say no strongly but I would say no. Because it should be installed into `moduledir`.
Installing other than `moduledir` should be done with care, clear intentions and purpose.

`--enable-strict-locations` is an undocumented developer's option.

**Comment by gautaz** [comment]
> > Thanks for the tip. I did try --enable-strict-locations but not with a moduledir setting.
> 
> Maybe you meant `--enable-strict-locations` with custom `--prefix`.

To clarify, I did try `./configure --disable-strict-locations --prefix=/opt/xorgxrdp`
Using `--enable-strict-locations` seems a bit odd as it would mean the reverse of what is intended...

> I do not say no strongly but I would say no. Because it should be installed into `moduledir`.
> Installing other than `moduledir` should be done with care, clear intentions and purpose.

I needed to use it in a building stage of a Dockerfile, hence the need to put the installed file in a clear location before reusing them in another stage.
