### ISSUE TITLE
Built error  ‘struct xrdp_client_info’ has no member named ‘version’

### ISSUE THREAD

**Issue by jorpilo** [neutrinolabs/xorgxrdp#189]
I am trying to build the devel branch however I am getting the following erros: 

rdpClientCon.c: In function ‘rdpClientConProcessMsgClientInfo’:
rdpClientCon.c:842:31: error: ‘struct xrdp_client_info’ has no member named ‘version’
  842 |     if (clientCon->client_info.version != CLIENT_INFO_CURRENT_VERSION)
      |                               ^
rdpClientCon.c:842:43: error: ‘CLIENT_INFO_CURRENT_VERSION’ undeclared (first use in this function                  )
  842 |     if (clientCon->client_info.version != CLIENT_INFO_CURRENT_VERSION)
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
rdpClientCon.c:842:43: note: each undeclared identifier is reported only once for each function it                   appears in
rdpClientCon.c:846:42: error: ‘struct xrdp_client_info’ has no member named ‘version’
  846 |                    clientCon->client_info.version));
      |                                          ^
rdpClientCon.c:56:43: note: in definition of macro ‘LLOGLN’
   56 |     do { if (_level < LOG_LEVEL) { ErrorF _args ; ErrorF("\n"); } } while (0)
      |                                           ^~~~~
make[3]: *** [Makefile:677: rdpClientCon.lo] Error 1
make[3]: Leaving directory '/home/jorpilo/.cache/paru/clone/xorgxrdp-devel-git/src/xorgxrdp/module                  '
make[2]: *** [Makefile:696: all-recursive] Error 1
make[2]: Leaving directory '/home/jorpilo/.cache/paru/clone/xorgxrdp-devel-git/src/xorgxrdp/module                  '
make[1]: *** [Makefile:435: all-recursive] Error 1
make[1]: Leaving directory '/home/jorpilo/.cache/paru/clone/xorgxrdp-devel-git/src/xorgxrdp'
make: *** [Makefile:367: all] Error 2

I am assuming this is related to #184 and commit 7ad1981. @matt335672 Is it missing to modify the rdpClientCon.h with the client info? Latest commit of the .h file is Jun

**Comment by metalefty** [comment]
Do you refer `xrdp_client_info` that has `version` member?

**Comment by jorpilo** [comment]
how? where is it defined? I just downloaded the source code and tried to compile it with make.

**Comment by metalefty** [comment]
xorgxrdp requires xrdp source to compile. You should already have the xrdp source code. Make sure the xrdp source has `version` member in `xrdp_client_info`.

**Comment by matt335672** [comment]
@jorpilo - see #184 and neutrinolabs/xrdp#1813 where this member was added to both xorgxrdp and xrdp. You need both products to match.

The irony is the point of these changes is to add mismatch detection into these two products at run-time!

Does that make sense?

Thanks.

**Comment by jorpilo** [comment]
Yeah completely understand now. Thanks for the info! It's a version mismatch at compilation time hahaha.
