### ISSUE TITLE
AddEnabledDevice and RemoveEnabledDevice symbols missing on Fedora 25

### ISSUE THREAD

**Issue by proski** [neutrinolabs/xorgxrdp#19]
I can compile xorgxrdp on Fedora 25 with some warnings, but I cannot use it without changing the code. Two symbols are unresolved: AddEnabledDevice and RemoveEnabledDevice.

Those symbols are not in the headers. I looked up those symbols, and I see that other Xorg drivers migrated to x86AddEnabledDevice and x86RemoveEnabledDevice. But those drivers were already using the InputInfoPtr type (a pointer to struct _InputInfoRec) consumed by the xf86* functions.

That is not the case for xorgxrdp. The file using AddEnabledDevice and RemoveEnabledDevice, rdpClientCon.c, doesn't even seem to deal much with input drivers.

It's interesting that AddEnabledDevice is called twice, but RemoveEnabledDevice only once. I replaced those calls with log messages. xorgxrdp started working for me. I see that both calls to AddEnabledDevice are made. As for RemoveEnabledDevice, it is not called as all if logging out from the session. It is called once if disconnecting without logging out.

Those function calls are present in X11rdp as well. They were present in the first commit that introduced X11rdp.

I suspect that using those functions on sockets is not needed, even for older X11 API.

xorg header version: xorg-x11-server-devel-1.19.0-0.3.20161026.fc25.x86_64

**Comment by jsorg71** [comment]
We need AddEnabledDevice so we can get a callback when data comes in to the unix domain socket.
It looks like they changed the API to use SetNotifyFd and RemoveNotifyFd.
I'll make the change.

**Comment by jsorg71** [comment]
Ok, pushed butI didn't test Fedora 25, I'll get a y=system setup soon.
On another note, it is interesting that RemoveEnabledDevice is not called twice but AddEnabledDevice is.
That looks wrong.

**Comment by jsorg71** [comment]
ok, I added a call to rdpClientConRemoveEnabledDevice

**Comment by proski** [comment]
The issue is fixed, resolving.
