### ISSUE TITLE
Can't find <drm_fourcc.h> when compiling

### ISSUE THREAD

**Issue by bogo-y** [neutrinolabs/xorgxrdp#198]
I want to use glamor, so I excuted "./configure --enable-glamor" and then excuted "make". But the process was interrupted due to <drm_fourcc.h> could not be found. If I don't use "--enable-glamor" it will be compiled successfully. You can see the details in paste.ubuntu.com/p/DqrwcjQKRF/.

**Comment by bogo-y** [comment]
By the way, I can use remote desktop with X.Org X Server 1.20.13 and xorgxrdp 0.2.17-1 now. However the bad performance made me try to enable GPU.

**Comment by jsorg71** [comment]
We should add that to the check when building
You can see what package provides a file on Debian with
dpkg -S /usr/include/libdrm/drm_fourcc.h
In this case it's in libdrm-dev

**Comment by bogo-y** [comment]
> We should add that to the check when building You can see what package provides a file on Debian with dpkg -S /usr/include/libdrm/drm_fourcc.h In this case it's in libdrm-dev

I am using Manjaro and I can't find libdrm-dev in AUR. But libdrm can be installed and it also has drm_fourcc.h and drm.h. Is there any way to make it available when compiling?

**Comment by wanyoou** [comment]
two solutions:
1. need to `export CFLAGS="$CFLAGS -I/usr/include/libdrm"` before running `./configure`.
2. execute `make EXTRA_FLAGS="-I/usr/include/libdrm"` instead of `make`.

reference: [[SOLVED] Adding an include location to a build](https://bbs.archlinux.org/viewtopic.php?id=260600)

**Comment by metalefty** [comment]
libdrm has .pc file for pkg-config. Using pkg-config to adjust include path and library path would be better.
