### ISSUE TITLE
populate DRI2InfoRec driverNames

### ISSUE THREAD

**Issue by akarl10** [neutrinolabs/xorgxrdp#215]
When using a underlying egl driver for rendering it is possible to use hardware decoding and possibly also encoding capabilities for video.

DRI2InfoRec has a list of driver names that should be used. intel cards need special treatment for vdpau. This is currently done in the intel display driver and xorg's modesetting driver (see hw/xfree86/drivers/modesetting/dri2.c function ms_dri2_screen_init).

I would suggest to do the same in the xorgxrdp driver (namely xrdpdri2.c)

I've already tried this on my system and could also make a push request for this change if you agree with that idea

**Comment by Nexarian** [comment]
Actually I would prefer that you propose a PR in the devel branch https://github.com/neutrinolabs/xorgxrdp/blob/devel/xrdpdev/xrdpdri2.c and then I can rebase my branch off of it. We should do as much as possible to avoid working in branches.

This presupposes that this change would not hurt current production use-cases, which it doesn't seen like it would.

Excellent work and I look forward to seeing your PR!
