### ISSUE TITLE
macOS Install Errors

### ISSUE THREAD

**Issue by jerick70** [neutrinolabs/xorgxrdp#245]
I'm trying to install xrdp and xorgrdp with xQuartz on an Intel Mac Mini .  I can compile and install xrdp fine.  When I try to install xorgxrdp I receive an error 2.  I've also received an error 1 with basically the same error.  Here's the arguments I'm using to compile and install xorgrdp and the full I'm getting.  Any help would be very appreciated.

I've tried to find the macOS install instructions but haven't found them.

xrdp:
./bootstrap
./configure PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
make
sudo make install

xorgxrdp:
./bootstrap
./configure PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig
make
sudo make install

xorgxrdp error when running make:
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in module
Making all in amd64
  NASM     a8r8g8b8_to_a8b8g8r8_box_amd64_sse2.lo
  NASM     a8r8g8b8_to_nv12_box_amd64_sse2.lo
  NASM     cpuid_amd64.lo
  NASM     i420_to_rgb32_amd64_sse2.lo
  NASM     uyvy_to_rgb32_amd64_sse2.lo
  NASM     yuy2_to_rgb32_amd64_sse2.lo
  NASM     yv12_to_rgb32_amd64_sse2.lo
  CCLD     libxorgxrdp-asm.la
  CC       rdpDraw.lo
In file included from rdpDraw.c:37:
In file included from /opt/X11/include/xorg/xf86.h:44:
In file included from /opt/X11/include/xorg/xf86str.h:37:
/opt/X11/include/xorg/misc.h:74:10: fatal error: 'X11/Xosdefs.h' file not found
#include <X11/Xosdefs.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [rdpDraw.lo] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by matt335672** [comment]
I'm closing this, as we can't yet provide support for MacOS as a github issue.

Check out these resources, which may well help:-
- #187 
- https://github.com/neutrinolabs/xrdp/wiki/Building-on-OSX-(not-official)
- https://gitter.im/neutrinolabs/xrdp-mac
