### ISSUE TITLE
xorg does not start with xorgxrdp 0.9.19 and xrdp 0.9.21.1

### ISSUE THREAD

**Issue by Blind55** [neutrinolabs/xorgxrdp#246]
Using Arch:
Name            : xrdp
Version         : 0.9.21.1-1
Description     : An open source remote desktop protocol (RDP) server
Architecture    : x86_64
URL             : https://github.com/neutrinolabs/xrdp
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : libxrandr  fuse  libfdk-aac  ffmpeg  imlib2
Optional Deps   : tigervnc [installed]
                  tightvnc
                  realvnc-vnc-server
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 2.32 MiB
Packager        : Unknown Packager
Build Date      : Thu 05 Jan 2023 04:43:18 PM MST
Install Date    : Thu 05 Jan 2023 04:43:58 PM MST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

When I start a session with freeRDP 2:2.9.0-1, I can log in, but sesman returns with a "could not connect" when using the Xorg session option. I can run fine with TigerVNC and a VNC login via xrdp (I assume that this is slower than via xorgxrdp).
I am fairly certain that it is Xorg not starting correctly with xorgxrdp that messes things up, but I am happy to try things out, providing logs, etc.

**Comment by matt335672** [comment]
Hi @Blind55 

First things to check:-
- sesman log file. That contains the command which is used to start the Xorg server. Try that on the command line, and see what you get.
- `~/.xorgxrdp.*.log` files contain information on the operation of xorgxrdp, if they exist at all.

Please update us on what you find.

**Comment by Blind55** [comment]
@matt335672 Many thanks for your reply.
Below is the section of the xrdp-sesman log. 

> [20230106-09:36:43] [INFO ] Socket 12: AF_INET6 connection received from ::1 port 48180
[20230106-09:36:43] [INFO ] Terminal Server Users group is disabled, allowing authentication
[20230106-09:36:43] [INFO ] ++ created session (access granted): username Blind55, ip ::ffff:xxx.xxx.xxx.xxx:54576 - socket: 12
[20230106-09:36:43] [INFO ] starting Xorg session...
[20230106-09:36:43] [INFO ] Starting session: session_pid 40106, display :11.0, width 2400, height 1500, bpp 24, client ip ::ffff:xxx.xxx.xxx.xxx:54576 - socket: 12, user name Blind55
[20230106-09:36:43] [ERROR] sesman_data_in: scp_process_msg failed
[20230106-09:36:43] [ERROR] sesman_main_loop: trans_check_wait_objs failed, removing trans
[20230106-09:36:43] [INFO ] [session start] (display 11): calling auth_start_session from pid 40106
[20230106-09:36:43] [INFO ] Starting X server on display 11: Xorg :11 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
[20230106-09:36:52] [WARN ] Timed out waiting for X server on display 11 to startup
[20230106-09:36:52] [INFO ] Session started successfully for user Blind55 on display 11
[20230106-09:36:52] [INFO ] Starting the xrdp channel server for display 11
[20230106-09:36:52] [INFO ] Session in progress on display 11, waiting until the window manager (pid 40107) exits to end the session
[20230106-09:36:53] [WARN ] Timed out waiting for X server on display 11 to startup
[20230106-09:36:53] [ERROR] There is no X server active on display 11
[20230106-09:36:53] [ERROR] A fatal error has occurred attempting to start the window manager on display 11, aborting connection
[20230106-09:36:53] [WARN ] Window manager (pid 40107, display 11) exited quickly (1 secs). This could indicate a window manager config problem
[20230106-09:36:53] [INFO ] Calling auth_stop_session and auth_end from pid 40106
[20230106-09:36:53] [INFO ] Terminating X server (pid 40108) on display 11
[20230106-09:36:53] [INFO ] Terminating the xrdp channel server (pid 40113) on display 11
[20230106-09:36:53] [INFO ] X server on display 11 (pid 40108) returned exit code 1 and signal number 0
[20230106-09:36:53] [INFO ] xrdp channel server for display 11 (pid 40113) exit code 0 and signal number 0
[20230106-09:36:53] [INFO ] cleanup_sockets:
[20230106-09:36:53] [INFO ] Process 40106 has exited
[20230106-09:36:53] [INFO ] ++ terminated session:  username Blind55, display :11.0, session_pid 40106, ip ::ffff:xxx.xxx.xxx.xxx:54576 - socket: 12

Using my user account, I attempted the command line
`Xorg :11 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log`
via IPMI, and that caused an error:
`Invalid argument -logfile with elevated privileges`
Running the command line *without* the apparently offending `-logfile` argument (and redirecting the output) seemed to have worked (although I didn't see a graphical screen, which I assume is ok):

>X.Org X Server 1.21.1.6
X Protocol Version 11, Revision 0
Current Operating System: Linux speckle2a 6.1.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 04 Jan 2023 16:28:15 +0000 x86_64
Kernel command line: initrd=\amd-ucode.img initrd=\initramfs-linux.img root=PARTUUID=aebfd79f-239a-41c3-9afd-d38712ffba6b rw
>
>Current version of pixman: 0.42.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.21.log", Time: Fri Jan  6 10:18:13 2023
(++) Using config file: "/etc/X11/xrdp/xorg.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
xorgxrdpSetup:
xrdpdevSetup:
rdpmousePlug:
rdpkeybPlug:
rdpIdentify:
rdpDriverFunc: op 10
rdpProbe:
rdpPreInit:
rdpScreenInit: virtualX 800 virtualY 600 rgbBits 8 depth 24
rdpScreenInit: pfbMemory bytes 1920000
rdpScreenInit: pfbMemory 0x7f52e3ac7010
rdpSimdInit: assigning yuv functions
rdpSimdInit: cpuid ax 1 cx 0 return ax 0x00830f10 bx 0x18180800 cx 0x7ed8320b dx 0x178bfbff
rdpSimdInit: sse2 amd64 yuv functions assigned
rdpClientConInit: disconnect idle session after [0] sec
rdpClientConInit: kill disconnected [0] timeout [0] sec
rdpClientConInit: do_touchpad_scroll_hack [0]
rdpXvInit: depth 24
rdpScreenInit: out
rdpCreateScreenResources:
rdpmousePreInit: drv 0x564b681a2c60 info 0x564b6846f480, flags 0x0
rdpmouseControl: what 0
rdpmouseDeviceInit:
rdpmouseCtrl:
rdpRegisterInputCallback: type 1 proc 0x7f52e3fc42c0
rdpmouseControl: what 1
rdpmouseDeviceOn:
rdpkeybPreInit: drv 0x564b681a2f60 info 0x564b68472600, flags 0x0
rdpkeybControl: what 0
rdpkeybDeviceInit:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpRegisterInputCallback: type 0 proc 0x7f52e3fbf920
rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpmouseControl: what 2
rdpmouseDeviceOff:
rdpkeybControl: what 2
rdpkeybDeviceOff:
xorgxrdpDamageDestroy:
rdpkeybControl: what 3
rdpkeybUnInit: drv 0x564b681a2f60 info 0x564b68472600, flags 0x0
rdpUnregisterInputCallback: proc 0x7f52e3fbf920
rdpmouseControl: what 3
rdpmouseUnInit: drv 0x564b681a2c60 info 0x564b6846f480, flags 0x0
rdpUnregisterInputCallback: proc 0x7f52e3fc42c0
rdpCloseScreen:
xorgxrdpDownDown:
xorgxrdpDownDown: 1
rdpClientConDeinit:
rdpClientConDeinit: deleting file /tmp/.xrdp/xrdp_display_21
rdpClientConDeinit: deleting file /tmp/.xrdp/xrdp_disconnect_display_21
(II) Server terminated successfully (0). Closing log file.

Unfortunately, there is no `~/.xorgxrdp.*.log` file from the 'regular' call when logging in with freeRDP.

**Comment by matt335672** [comment]
A problem here is that sesman is starting Xorg without a path. That runs the Xorg wrapper and that won't work on modern systems.

If you don't know what I mean by "Xorg wrapper", this command will show you that the standard Xorg command is just a shell script:-

```
cat $(which Xorg)
```

Have a look in `/etc/xrdp/sesman.ini`. Under the `[Xorg]` section there will be a `param=Xorg` line. From memory for Arch that should be `param=/usr/lib/Xorg` instead. 

You can check that by seeing if this command works on the command line:-

```
/usr/lib/Xorg :11 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

Have I explained that well enough?

**Comment by Blind55** [comment]
Thank you again for your quick, and very clear, reply. I am getting:
>$ which Xorg
/sbin/Xorg
$ ls -al /sbin/Xorg
-rwxr-xr-x 1 root root 271 Dec 19 05:35 /sbin/Xorg

In Arch, /sbin/ is just a link to /usr/bin, and - as you say - that script either executes Xorg.wrap (if it exists, to run with suid), or /usr/lib/Xorg directly. I have made the change you suggest to the /etc/xrdp/sesman.ini file:
>[Xorg]
; Specify the path of non-suid Xorg executable. It might differ depending
; on your distribution and version. Find out the appropriate path for your
; environment. The typical path is known as follows:
;
; Fedora 26 or later    :  param=/usr/libexec/Xorg
; Debian 9 or later     :  param=/usr/lib/xorg/Xorg
; Ubuntu 16.04 or later :  param=/usr/lib/xorg/Xorg
; Arch Linux            :  param=/usr/lib/Xorg
; CentOS 7              :  param=/usr/bin/Xorg or param=Xorg
; CentOS 8              :  param=/usr/libexec/Xorg
; FreeBSD (from 2022Q4) :  param=/usr/local/libexec/Xorg
; 
param=/usr/lib/Xorg
; Leave the rest parameters as-is unless you understand what will happen.
param=-config
param=xrdp/xorg.conf
param=-noreset
param=-nolisten
param=tcp
param=-logfile
param=.xorgxrdp.%s.log

This did solve the issue. Thank you very much again.

[I also looked back in the AUR page for xrdp (something I should probably have done first), and there the suggestion that you make was the same - I apologize profusely for the noise here.]
