### ISSUE TITLE
Xorg not showing on login screen

### ISSUE THREAD

**Issue by sabman3** [neutrinolabs/xorgxrdp#250]
I know it's probably been asked before but I can't find the answer., I have both xrdp and xorgxrdp (from EPEL) installed on a RHEL 9 system. In the README for xorgxrdp, it says one of the options on the login screen should be Xorg. However all that is showing for me is xvnc. Is there another step I'm missing?

**Comment by matt335672** [comment]
@sabman3 - the options displayed are listed in `/etc/xrdp/xrdp.ini`. I believe for EPEL systems you need to uncomment the `[Xorg]` section to use it.

**Comment by sabman3** [comment]
That was it. Thanks for the help!
