### ISSUE TITLE
configure: error: Package requirements (xrdp >= 0.9.80) were not met

### ISSUE THREAD

**Issue by D3vil0p3r** [neutrinolabs/xorgxrdp#252]
Hello,
I'm building xorgxrdp but when I run `./configure` as explained in the README.md file, I get the following error:
```
<SNIP>
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking CFLAGS for maximum warnings... -Wall
checking whether C compiler accepts -Wwrite-strings... yes
checking for __attribute__((format))... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XORG_SERVER... yes
checking for XRDP... no
configure: error: Package requirements (xrdp >= 0.9.80) were not met:

Package dependency requirement 'xrdp >= 0.9.80' could not be satisfied.
Package 'xrdp' has version '0.9.19', required version is '>= 0.9.80'

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables XRDP_CFLAGS
and XRDP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
I'm working on Arch Linux, but the latest version of Xrdp is 0.9.21, so it still didn't reach the 0.9.80 version reported in the output above...

**Comment by matt335672** [comment]
Hi @D3vil0p3r 

It looks like you're building the devel version of xorgxrdp.

Get down the tarball for the v0.9.19 release and try that instead. It has this dependency in it:-

https://github.com/neutrinolabs/xorgxrdp/blob/d463bad9639c910fadc2f30dac473c7688b11cfc/configure.ac#L33-L36

**Comment by D3vil0p3r** [comment]
Thank you @matt335672 
Should I close the issue?

**Comment by matt335672** [comment]
If that is indeed what's happened, yes. Feel free to close it.
