### ISSUE TITLE
GFX: move to posix shm

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xorgxrdp#269]
xorgxrdp is moved to posix shm:
https://github.com/neutrinolabs/xorgxrdp/commit/aafceeb4881acf38d6edc48936b61f637c469756

Rebase GFX xorgxrdp to posix shm ver.

**Comment by metalefty** [comment]
@Nexarian @jsorg71 Can you rebase?

**Comment by Nexarian** [comment]
I have been working on mainline_merge_shm. I'll switch mainline_merge to that branch tonight and rebase.
