### ISSUE TITLE
Compile error on Ubuntu 16.04 amd64

### ISSUE THREAD

**Issue by veart** [neutrinolabs/xorgxrdp#27]
Making all in module
make[2]: Entering directory '/home/veart/Downloads/xrdp/xorgxrdp/module'
/bin/bash ../libtool --mode=compile --tag NASM ./nasm_lt.sh nasm -felf64 -DELF -D__x86_64__ -I. -I. amd64/yv12_to_rgb32_amd64_sse2.asm -o amd64/yv12_to_rgb32_amd64_sse2.lo
libtool:   error: ignoring unknown tag NASM
libtool: compile:  ./nasm_lt.sh nasm -felf64 -DELF -D__x86_64__ -I. -I. amd64/yv12_to_rgb32_amd64_sse2.asm  -fPIC -DPIC -o amd64/.libs/yv12_to_rgb32_amd64_sse2.o
nasm -felf64 -DELF -D__x86_64__ -I./ -I./ amd64/yv12_to_rgb32_amd64_sse2.asm -DPIC -o amd64/.libs/yv12_to_rgb32_amd64_sse2.o
amd64/yv12_to_rgb32_amd64_sse2.asm:256: fatal: expected `%endif' before end of file
Makefile:863: recipe for target 'amd64/yv12_to_rgb32_amd64_sse2.lo' failed
make[2]: *** [amd64/yv12_to_rgb32_amd64_sse2.lo] Error 1
make[2]: Leaving directory '/home/veart/Downloads/xrdp/xorgxrdp/module'
Makefile:410: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/veart/Downloads/xrdp/xorgxrdp'
Makefile:342: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by proski** [comment]
Fixed in 0a355b061bffc27d14952e4790298e14644bc081

The commit is in devel, but it hasn't been merged into master yet.

**Comment by veart** [comment]
Thank you. It work now!
