### ISSUE TITLE
Can't mount drives after xrdp update

### ISSUE THREAD

**Issue by bananas123f** [neutrinolabs/xorgxrdp#281]
Can't mount any drives in Ubuntu 22.04 after xrdp updated. Everytime I try to mount a drive it says "unable to access "drive_name" An operation is already pending".

When I log in to the computer physically all drives mount normally. What's up with this, how do I fix this?

**Comment by metalefty** [comment]
Multiple posting of: https://github.com/neutrinolabs/xrdp/issues/2934
