### ISSUE TITLE
'struct _GC' has no member named 'clientClipType'

### ISSUE THREAD

**Issue by itamarjp** [neutrinolabs/xorgxrdp#3]
the module directory fails to compile with the flowing error.

any help about that ?

Making all in module
make[2]: Entering directory '/home/itamar/fedora/xrdp-itamarjp/xrdp/xorgxrdp/module'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/X11/dri  -I../../common -DSIMD_USE_ACCEL=1  -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c -o rdpDraw.lo rdpDraw.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -fvisibility=hidden -I/usr/include/xorg -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/X11/dri -I../../common -DSIMD_USE_ACCEL=1 -g -O2 -MT rdpDraw.lo -MD -MP -MF .deps/rdpDraw.Tpo -c rdpDraw.c  -fPIC -DPIC -o .libs/rdpDraw.o
rdpDraw.c: In function 'rdpDrawGetClip':
rdpDraw.c:69:20: error: 'struct _GC' has no member named 'clientClipType'
         switch (pGC->clientClipType)
                    ^
rdpDraw.c:80:27: error: 'struct _GC' has no member named 'clientClipType'
                        pGC->clientClipType));
                           ^
rdpDraw.c:51:43: note: in definition of macro 'LLOGLN'
     do { if (_level < LOG_LEVEL) { ErrorF _args ; ErrorF("\n"); } } while (0)
                                           ^
rdpDraw.c:114:28: error: 'struct _GC' has no member named 'clientClipType'
                 switch (pGC->clientClipType)
                            ^
rdpDraw.c:130:35: error: 'struct _GC' has no member named 'clientClipType'
                                pGC->clientClipType));
                                   ^
rdpDraw.c:51:43: note: in definition of macro 'LLOGLN'
     do { if (_level < LOG_LEVEL) { ErrorF _args ; ErrorF("\n"); } } while (0)
                                           ^
Makefile:577: recipe for target 'rdpDraw.lo' failed
make[2]: **\* [rdpDraw.lo] Error 1
make[2]: Leaving directory '/home/itamar/fedora/xrdp-itamarjp/xrdp/xorgxrdp/module'
Makefile:406: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/itamar/fedora/xrdp-itamarjp/xrdp/xorgxrdp'
Makefile:338: recipe for target 'all' failed
make: **\* [all] Error 2

**Comment by jsorg71** [comment]
Can you check what version of Xorg this is?

**Comment by itamarjp** [comment]
xorg-x11-server-devel-1.17.2-1.fc22.x86_64

**Comment by itamarjp** [comment]
$ xdpyinfo | grep version
version number:    11.0

**Comment by clandmeter** [comment]
Having the same issue with xorg-server-dev-1.17.2-r1

**Comment by jsorg71** [comment]
Things like this are expected.  They change the Xorg internals sometimes.
I'll look through their git history to see what they changed.

**Comment by jsorg71** [comment]
Looks like Intel's open source driver had similar issue.
https://bugs.freedesktop.org/show_bug.cgi?id=85581

**Comment by jsorg71** [comment]
Here is link to their fix.
http://lists.x.org/archives/xorg-commit/2014-October/037287.html

Basically, the clientClip is always a region now so we don't have to check the type anymore.  Used to be either a PixmapPtr or a RegionPtr.

**Comment by clandmeter** [comment]
Do you have a patch we could try?

**Comment by jsorg71** [comment]
Just spent several hours installing fedora 22.  Always hangs.
Fedora 21 ok.
Does any other distro have this later version?

**Comment by clandmeter** [comment]
I am using alpinelinux.org. But I guess arch also has one of the latest version.

**Comment by jsorg71** [comment]
maybe fixed with
devel branch
cd077979ebeb81a6e85a9ba7f9c463beda1606ba

**Comment by jsorg71** [comment]
@clandmeter
I like AlpineLinux.
You should type up an install how to for xrdp.  Similar to
https://github.com/neutrinolabs/xrdp/wiki/Building-on-Fedora-19---20

**Comment by clandmeter** [comment]
I just added the git version to our testing repo edge/testing. x86 fails to build because of texrel:

```
>>> xrdp-git-xorgxrdp*: Preparing subpackage xrdp-git-xorgxrdp...
>>> xrdp-git-xorgxrdp*: Stripping binaries
>>> xrdp-git*: Running postcheck for xrdp-git-xorgxrdp
>>> ERROR: xrdp-git*: Found textrels:
TEXTREL  /home/buildozer/aports/testing/xrdp-git/pkg/xrdp-git-xorgxrdp/usr/lib/xorg/modules/libxorgxrdp.so
>>> ERROR: xrdp-git*: prepare_subpackages failed
>>> ERROR: xrdp-git: all failed
>>> xrdp-git: Uninstalling dependencies...
```

its split into two packages, xrdp-git and xrdp-git-xorgxrdp

http://pkgs.alpinelinux.org/package/testing/x86_64/xrdp-git
http://pkgs.alpinelinux.org/package/testing/x86_64/xrdp-git-xorgxrdp

I have no experiance with xrdp, but i would like to build a headless xorg server in our lxc enviorment to test Xorg packages we build. Would that be possible with the xorg drivers? I cant seem to find much info regarding this kind of setup, most of them are based on vnc which i prefer to prevent.

**Comment by jsorg71** [comment]
This is fixed, closing.
