### ISSUE TITLE
No release assets on tagged v0.10.1 release?

### ISSUE THREAD

**Issue by dropwhile** [neutrinolabs/xorgxrdp#311]
The tagged [v0.10.1 release][1] does not appear to have release assets (autoconf prepared .tar.gz, etc) added to it.

Was this intentional or accidental?

[1]: https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.10.1

**Comment by metalefty** [comment]
It happened by accident. I will add it soon, thanks!

**Comment by metalefty** [comment]
Added, sorry for the inconvenience.

**Comment by dropwhile** [comment]
No worries! Thanks for the quick fix. ❤️
