### ISSUE TITLE
unable to build latest release (0.10.3)

### ISSUE THREAD

**Issue by alexmyczko** [neutrinolabs/xorgxrdp#360]
```
checking for xrdp >= 0.10.2... no
configure: error: Package requirements (xrdp >= 0.10.2) were not met:

Package dependency requirement 'xrdp >= 0.10.2' could not be satisfied.
Package 'xrdp' has version '0.10.1', required version is '>= 0.10.2'

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.
```

but xrdp 0.10.2 release is non existant?

**Comment by matt335672** [comment]
Hi Alex,

It's not out yet, but it's pretty imminent.

**Comment by metalefty** [comment]
See the release note: https://github.com/neutrinolabs/xorgxrdp/releases/tag/v0.10.3

**Comment by sshaikh** [comment]
Thanks for clearing this up. The confusion is in that xrdp v0.10.2 doesn't seem to be available yet. Seems this has jumped the gun slightly?

Is there a reason why the version numbers are out of sync? I might be making it up but I recall previously they were equal?

**Comment by kfoxirl** [comment]
Hi guys, is the xrdp v.10.2 release delayed?

**Comment by metalefty** [comment]
We always release xorgxrdp precedes xrdp 1 day to 1 week. This is absolutely normal thing. Because We have too much things to do in a short period of time if we release everything at the same time.


Thanks for being keen to new releases, don't rush, hang tight for a while. 

This release is a part of "December 2024 release" and the release process is like "On your mark, get set (release xorgxrdp), go (release xrdp)!"

**Comment by kfoxirl** [comment]
> We always release xorgxrdp precedes xrdp 1 day to 1 week. This is absolutely normal thing. Because We have too much things to do in a short period of time if we release everything at the same time.
> 
> Thanks for being keen to new releases, don't rush, hang tight for a while.
> 
> This release is a part of "December 2024 release" and the release process is like "On your mark, get set (release xorgxrdp), go (release xrdp)!"

Got it, thanks for letting me know. I will have to figure out how to roll back to a working version, I got a bit update happy working on a problem lol

**Comment by metalefty** [comment]
Released [v0.10.2-rc.1](https://github.com/neutrinolabs/xrdp/releases/tag/v0.10.2-rc.1). I think you can build xorgxrdp v0.10.3 against this.  v0.10.2 will be out within a day or two.

**Comment by kfoxirl** [comment]
Awesome!

**Comment by metalefty** [comment]
Everything is out now.
