### ISSUE TITLE
Need a license file

### ISSUE THREAD

**Issue by proski** [neutrinolabs/xorgxrdp#37]
xorgxrdp should not be released without a license. The source files appear to carry some variant of the X.Org license.

https://www.x.org/releases/X11R7.7/doc/xorg-docs/License.html

But ultimately it should be up to the authors of the code.

The common convention is to put the license to a file called COPYING in the top source directory.

**Comment by itamarjp** [comment]
+1

**Comment by proski** [comment]
PR #39 submitted

**Comment by metalefty** [comment]
COPYING doesn't include copyright year and copyright holders yet.
Close after adding them.
