### ISSUE TITLE
Tasks should be done before next release 

### ISSUE THREAD

**Issue by metalefty** [neutrinolabs/xorgxrdp#40]
The next xorgxrdp release will be December 2016, at the same time as xorgxrdp.
Everything is done means it's time to release.  xorgxrdp can be released before next xrdp release if all done.

To be in time for next Debian (9/stretch), soft deadline is middle of December, hard deadline is end of December. 

- [x] Close all issues which have next release milestone
- [x] Decide next version number
- [x] Add copyright holder and copyright year to COPYING

**Comment by proski** [comment]
- [ ] `readme.txt` should be completely rewritten, possibly converted to markdown.

**Comment by metalefty** [comment]
I started to work on new README at [wiki](https://github.com/neutrinolabs/xorgxrdp/wiki/README).

**Comment by proski** [comment]
Date based versions are not good. They miss an opportunity to tell the user about the amount of the changes. They are not suitable for security releases. Say, the 2016.12 version is so good that we don't make a release for another 10 years. In 2026, 2016.12 would look very old. Then we release 2026.12. A month later, we find a security issue that affects both 2016.12 and 2026.12. How would we name the fixed version?

Typical uses of date versions are scheduled releases, which always have a lot of changes. Date version are also suitable for the cased when users are not supposed to decide whether to upgrade ("use 2016.12 or you are fired").

**Comment by metalefty** [comment]
I meant "2016.12" as a pointer of "next release in December 2016". Not a version.

**Comment by proski** [comment]
Sure, just wanted to make sure the label doesn't stick.

**Comment by proski** [comment]
I believe #42 should go to the next release. It fixes crash in all gtk3 programs with older Xorg. The end user impact is significant, the change is minimal.

**Comment by metalefty** [comment]
OK, I added milestone.

**Comment by metalefty** [comment]
If no other opinions, the next version will be "0.2.0".

**Comment by proski** [comment]
Sounds good to me.

**Comment by metalefty** [comment]
I think everything has been done. Let's release.

**Comment by proski** [comment]
Make sure to mention the dependency on the yet to be released xrdp 0.9.1 in the release notes.

**Comment by speidy** [comment]
xorgxrdp v0.2.0 has been released.
