### ISSUE TITLE
xrdp multimon to LTSP server with LDAP

### ISSUE THREAD

**Issue by Michel-5** [neutrinolabs/xorgxrdp#54]
Hello all,

First of all i need to say that the code you guys give here is awesome!

I also want to say in advance that my english is terrible, so sorry for that.

For a project i've build multiple Linux Terminal Server Projects with users who authenticate trough LDAP because some users work on different locations. I want to build it in a way that users can login through RDP. So for an example, if you have 2 locations and a persons account is on location 1 and he or she wants to work from location 2, he or she needs a RDP connection.

When i build XRDP and Xorg from neutrinolabs i get the local users to work with dual screen. But when i want to login with a LDAP User, i only get a black screen.

When i use the X11rdp-o-Matic script, i only get it working with one monitor because that script build's it like a xvnc server.

I hope someone knows the answer for this problem.

Thanks in advance for the use of your time

Greetings Michel

**Comment by proski** [comment]
Let's close this issue in favor of https://github.com/neutrinolabs/xrdp/issues/597

The description is not quite clear, but I seriously doubt that the fix would be in the xorgxrdp code.
