### ISSUE TITLE
segfault and disconnect on debian server

### ISSUE THREAD

**Issue by cypa** [neutrinolabs/xorgxrdp#62]
Got X-server segfault and so client disconnect on both windows client and linux client, see logs below.
xorgxrdp and xrdp was compiled from latest source tarball on Debian 8.6.

Connect using windows 10 standart client 
and ubuntu 14.04 standart xfreerdp 1.0.2 with command 
`xfreerdp -f -u vasya -p skejlsuhd 46.4.NN.NN:3398 -z -x b -K Russian`

[xfreerdp1.xorgxrdp.13.log.txt](https://github.com/neutrinolabs/xorgxrdp/files/721025/xfreerdp1.xorgxrdp.13.log.txt)
[xfreerdp1.xorgxrdp.11.log.txt](https://github.com/neutrinolabs/xorgxrdp/files/721027/xfreerdp1.xorgxrdp.11.log.txt)
[win10.xorgxrdp.15.log.txt](https://github.com/neutrinolabs/xorgxrdp/files/721026/win10.xorgxrdp.15.log.txt)

**Comment by cypa** [comment]
no ideas?

**Comment by metalefty** [comment]
I also hit the same issue #9.

**Comment by metalefty** [comment]
can you reproduce segfault again with #64 patch? the log becomes more informative.

**Comment by cypa** [comment]
frankly, after apllying the #64 patch no segfaults occured so far

**Comment by metalefty** [comment]
sure. It isn't a fix.

**Comment by cypa** [comment]
yes, it is still there: no more segfaults and current RDP session is going for 20 hours and continues to go ...
all I did:
- apllied #64 patch manually in vi
- make clean
- make
- sudo make install
that's it!

**Comment by metalefty** [comment]
Please show us the log when you reproduce segfaults.  I also hardly reproduce segfaults.

**Comment by cypa** [comment]
I've got no segfaults since #64 patch applied
logs with segfaults attached to the top comment - that's all I have

**Comment by cypa** [comment]
this is the log of current alive RDP session
[xfreerdp.xorgxrdp.17.log.zip](https://github.com/neutrinolabs/xorgxrdp/files/726113/xfreerdp.xorgxrdp.17.log.zip)

**Comment by metalefty** [comment]
Yes, when you reproduce segfaults.

**Comment by moobyfr** [comment]
The log for xfreerdp1.xorgxrdp.13.log.txt is showing

[249760.685] rdpClientConSendMsg: overrun error len 33504 count 2

This indicate that you used the 0.2.0 version of xorgxrdp, and you probably hit #5 because of the "overrun error" which makes Xorg SEGV
As #5 is fixed, , could you test the HEAD version from xorgxrdp to be sure the issue is no mor represent.
If you can't reproduce it, this issue can be closed :)

**Comment by cypa** [comment]
installed from HEAD ... shall see what happens

**Comment by metalefty** [comment]
I haven't seen segfaults for months. Seems to be fixed?

**Comment by cypa** [comment]
HEAD on Ubuntu 16.04 do not show disconnects ...
