### ISSUE TITLE
Include config_ac.h ① in all files, and ② first, before anything else

### ISSUE THREAD

**Issue by mirabilos** [neutrinolabs/xorgxrdp#66]
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852617#42 for a lecture from GNU autoconf upstream:

> If the real-world package is not including config.h first, then that is                                     
> a bug in the real-world package that should be fixed there.  Autoconf                                       
> clearly documents that if you create config.h, it MUST be included                                          
> first, before any system headers.                                                                           

The [workaround](https://anonscm.debian.org/cgit/pkg-remote/xrdp.git/plain/debian/patches/lfs.diff?id=e17430063641d44f5596b5bfc1b32ac4ba39f9f1) I had to add to the xrdp Debian package to enable and fix Large File Support was… not nice. So, apparently, the correct fix involves having __every__ __single__ source file (`*.c`, but also C++ et al.) `#include "config_ac.h"` first, *before* __any__ other `#include` or nōn-preprocessor statement (the inclusion from various header files, such as `arch.h`, can then be removed).

**Comment by jsorg71** [comment]
Is this fixed by #72 ?

**Comment by mirabilos** [comment]
Possibly (see my comment there though).
