### ISSUE TITLE
compile fails on openSUSE

### ISSUE THREAD

**Issue by Cris70** [neutrinolabs/xorgxrdp#86]
Hi, I have followed the instructions for compiling xorgxrdp, but I have this issue:
```
cristiano@VD1SL001 [~/Downloads/xorgxrdp-0.2.0]$ LANG=C make
make  all-recursive
make[1]: Entering directory '/home/cristiano/Downloads/xorgxrdp-0.2.0'
Making all in module
make[2]: Entering directory '/home/cristiano/Downloads/xorgxrdp-0.2.0/module'
  CC       rdpDraw.lo
In file included from rdpDraw.c:40:0:
/usr/include/xorg/dixfontstr.h:30:33: fatal error: X11/fonts/libxfont2.h: No such file or directory
 #include <X11/fonts/libxfont2.h>
                                 ^
compilation terminated.
make[2]: *** [Makefile:646: rdpDraw.lo] Error 1
make[2]: Leaving directory '/home/cristiano/Downloads/xorgxrdp-0.2.0/module'
make[1]: *** [Makefile:422: all-recursive] Error 1
make[1]: Leaving directory '/home/cristiano/Downloads/xorgxrdp-0.2.0'
make: *** [Makefile:354: all] Error 2
```
I have tried installing various additional devel packages but I always have the same error, despite the fact that **the _configure_ command reports that everything is OK**.
Here are my installed packages:
```
cristiano@VD1SL001 [~/Downloads/xorgxrdp-0.2.0]$ LANG=C zypper se -i xorg 
Loading repository data...
Reading installed packages...

S | Name                   | Summary                                                                        | Type   
--+------------------------+--------------------------------------------------------------------------------+--------
i | xorg-cf-files          | Data files for the imake utility                                               | package
i | xorg-scripts           | Miscellaneous scripts for X                                                    | package
i | xorg-sgml-doctools     | Set of SGML entities and XML/CSS style sheets for building X.org documentation | package
i | xorg-x11               | Compatibility metapackage for X.Org sample applications                        | package
i | xorg-x11-Xvnc          | TigerVNC implementation of Xvnc                                                | package
i | xorg-x11-driver-input  | Compatibility metapackage for X.Org input drivers                              | package
i | xorg-x11-driver-video  | Compatibility metapackage for X.Org video drivers                              | package
i | xorg-x11-essentials    | Compatibility metapackage for X.Org core applications                          | package
i | xorg-x11-fonts         | X.Org fonts                                                                    | package
i | xorg-x11-fonts-core    | Core Fonts for X.Org                                                           | package
i | xorg-x11-libX11-ccache | X                                                                              | package
i | xorg-x11-server        | X                                                                              | package
i | xorg-x11-server-sdk    | X                                                                              | package
i | xorg-x11-server-source | Source code of X.Org server                                                    | package
i | xorg-x11-util-devel    | Compatibility metapackage for X11 development                                  | package
```
This is on my openSUSE Tumbleweed.

Any help?
Thank you in advance
Cris

**Comment by metalefty** [comment]
Probably libXfont is missing. Can you show me all installed packages?

**Comment by ttv20** [comment]
I success to make it on openSUSE Leap 42.2
I install xorg-x11-devel and it still not working, but the error change to:
`make  all-recursive
make[1]: Entering directory '/home/yhb/git/neutrinolabs/xorgxrdp'
Making all in module
make[2]: Entering directory '/home/yhb/git/neutrinolabs/xorgxrdp/module'
Making all in amd64
make[3]: Entering directory '/home/yhb/git/neutrinolabs/xorgxrdp/module/amd64'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/yhb/git/neutrinolabs/xorgxrdp/module/amd64'
make[3]: Entering directory '/home/yhb/git/neutrinolabs/xorgxrdp/module'
  CC       rdpDraw.lo
Assembler messages:
Fatal error: can't create .libs/rdpDraw.o: Permission denied
Makefile:583: recipe for target 'rdpDraw.lo' failed
make[3]: *** [rdpDraw.lo] Error 1
make[3]: Leaving directory '/home/yhb/git/neutrinolabs/xorgxrdp/module'
Makefile:602: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/yhb/git/neutrinolabs/xorgxrdp/module'
Makefile:411: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/yhb/git/neutrinolabs/xorgxrdp'
Makefile:342: recipe for target 'all' failed
make: *** [all] Error 2
`
So I did
`sudo make`
And it's work!

**Comment by Cris70** [comment]
@metalefty thank you!
Installing libXfont-devel and libXfont2-devel did the trick (I am not sure if both packages were necessary).
