### ISSUE TITLE
Latency / performance issues, rdpDeferredUpdateCallback

### ISSUE THREAD

**Issue by johnarnold** [neutrinolabs/xorgxrdp#87]
Latency with both mouse input and keyboard input (moving curser around).  Takes approx. twice as long to double-click and highlight a word in text editor, versus when using Xvnc.

Please see:
https://github.com/neutrinolabs/xrdp/issues/386

Xorg logs are full of:

[2756639.134] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.175] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.215] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.255] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.295] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.335] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655
[2756639.375] rdpDeferredUpdateCallback: reschedule rect_id 823656 rect_id_ack 823655

**Comment by jsorg71** [comment]
@johnarnold How are you measuring latency?  Is it visual perception or are you looking at TCP packet time?
To reduce draws sent to client, there is a time period the server waits before draw send to see if maybe it's doing to change again.  Similar to the idea behind Nagle's algorithm.
Both X11rdp and Xorg do this.  We could make this configurable and even allow a way to turn it off.

**Comment by johnarnold** [comment]
It's visual perception.  It's enough latency that it's easily noticeable.  Like maybe it's 200ms with Xvnc (annoying, but not a dealbreaker) and it's twice that or more with Xorg.  It should be pretty easy to repro -- I can switch back and forth trivially to see it, and I don't have any customizations.

If you have any suggestions on a better way to measure, I'm listening.

**Comment by johnarnold** [comment]
@jsorg71 Any suggestions?

**Comment by moobyfr** [comment]
what are your version for xrdp ?
during the 'lag', are you playing something like video ?
what is your RDP client ?

**Comment by jsorg71** [comment]
200ms with Xorg and X11rdp and 0ms with Xvnc seems strange.  I don't see that.  Is this a bandwidth issue?  I don't see how that can be either because X11rdp and Xorg should be less bandwidth.  Is this a VM environment where the 40ms delay in Xorg and X11rdp can be in accurate, ie tickless kernel.

**Comment by metalefty** [comment]
I rarely see that issue. I couldn't find out conditions though.
@johnarnold you're not alone :smile:

**Comment by johnarnold** [comment]
Hi,

$ sudo apt-cache policy xrdp
xrdp:
  Installed: 0.9.1-7
  Candidate: 0.9.1-7
  Version table:
 *** 0.9.1-7 100
        100 /var/lib/dpkg/status
     0.6.1-2 500
        500 http://azure.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

I don't do any video or media stuff.  No RemoteFX features as far as I know.  99% of time is spent in PyCharm.

This is connecting over long fat pipes (100Gbps) across the US (west coast to east coast). It's not a bandwidth issue that I can imagine.  Performance is acceptable with Xvnc -- it just noticeably lags with XorgX11rdp.

It is a VM server.   Can you expand on the 40ms delay and tickless kernel?   I'm familiar with tickless.. just wondering how X11rdp is affected differently than Xvnc.

**Comment by jsorg71** [comment]
I setup azure ubuntu vm and got xrdp installed.  I did not see any delay when using xrdp / xorgxrdp.  It actually preformed really well.
I can't test anymore now as Azure shut me down claiming I violated the use conditions. :)
I guess that is because I turned on port 3389 to my vm, I'm not sure.

**Comment by johnarnold** [comment]
I can give you an Azure VM with repro if that helps. Email me johnar @ microsoft.com

**Comment by jsorg71** [comment]
Thanks, I'll contact you.

**Comment by sblack1969** [comment]
@jsorg71 - I have the same mouse/keyboard latency issue as johnarnold.  My original post is neutrinolabs/xrdp#501.  I get the same rdpDeferredUpdateCallback log entries.  It works fine for vms running 12.04, but latency is very high under 14.04 and 16.04.  I've tried every possible configuration setting, have recompiled xrdp from source, nothing makes a difference.  Any suggestions?

**Comment by daniel-sullivan** [comment]
Interestingly I'm getting the exact same issue with the rdpDeferredUpdateCallback in the logs with a clean (Azure) install of Ubuntu zesty (17.04) with Xubuntu-desktop

**Comment by johnarnold** [comment]
@jsorg71 has a PR open for a fix: https://github.com/neutrinolabs/xorgxrdp/pull/92

Thanks Jay!

**Comment by sblack1969** [comment]
@jsorg71 I compiled the xorgxrdp-frame_diff branch from your PR, but it had no impact on the latency issue I am seeing.  I have a repro vm available - would you be willing to look at it if I opened it up to you?

**Comment by jsorg71** [comment]
This optimization is only for RemoteFX mode.  When using MSTSC, that means 32 bit color and LAN experience.

**Comment by sblack1969** [comment]
Would it be possible to get some help troubleshooting the latency issue I'm seeing?  I have a very basic vm setup already that you could access directly.  I've tried all sorts of settings but always get the same result.

**Comment by metalefty** [comment]
I also reproduce the issue with no RemoteFX mode, xorgxrdp= 6eadd1e32041dccfbb13df65f786e66e0349f59c. How is the network bandwidth consumption while the issue is occurring?

**Comment by sblack1969** [comment]
I have tried three different scenarios under 16.04 (1440 x 900 screen, 24 bpp):

1)  Local LAN connection - everything is smooth and fast

2)  Broadband connection (tls encryption) - there is still some visual lag when dragging an open window around, but it's workable

3)  Tunneled broadband connection (ipsec vpn) - unusable due to lag, drawing the background image is block by block and takes about 10 seconds for a (1440 x 900 screen), dragging an open window around is extremely choppy and slow

Under 12.04, all three scenarios work great.  When I tried to move to 14.04, the very slow performance started so I stayed on with 12.04 figuring I would wait to see if it was different under 16.04.  Under 16.04 the performance is identical to 14.04.

So did something fundamentally change in 12.04 relative to bandwidth requirements?  Is xrdp over an ipsec tunnel a viable option or has xrdp changed such that it now requires a lot more bandwidth than it used to?

**Comment by lnicola** [comment]
Another data point: I'm on a LAN (though on WiFi) and xorgxrdp is visibly laggier than Xvnc, yet I have no messages like those in the log.

**Comment by metalefty** [comment]
Generally, xrdp version is more important rather than OS (Ubuntu) version.

**Comment by sblack1969** [comment]
0.6.0 is running on my 12.04 server 
0.9.2 is running on my 16.04 server

**Comment by sblack1969** [comment]
@metalefty - Are there any settings that might improve performance when running 0.9.2 in a more bandwidth restricted situation (such as over a vpn)?  Were there any major changes in bandwidth requirements post 0.6.0?  I have a vm that you could access remotely if it helps.

**Comment by johnarnold** [comment]
@jsorg71 is RemoteFX in mstsc *only* when set to LAN, does WAN also enable it?

Reading from:
https://blogs.technet.microsoft.com/enterprisemobility/2012/08/23/remotefx-for-wan-overview-of-intelligent-and-adaptive-transports-in-windows-8-and-windows-server-2012/

**Comment by metalefty** [comment]
xrdp supports Remote FX of RDP 7.1. It requires connectionType==LAN. To enable RemoteFX on WAN, RDP 8.0 is needed and xrdp currently doesn't support it.

Further more, IIRC, RemoteFX on WAN is a part of GFX. We need to implement lots of features to enable RemoteFX on WAN.
https://msdn.microsoft.com/en-us/library/hh554846.aspx

> Furthermore, if the connectionType field of the Client Core Data ([MS-RDPBCGR] section 2.2.1.3.2) is set to any value other than CONNECTION_TYPE_LAN (0x06), then the RemoteFX server SHOULD NOT<2> indicate that the RemoteFX codec is supported, that is,

https://msdn.microsoft.com/en-us/library/ff635369.aspx#Appendix_A_Target_2

> Microsoft RDP 8.0 RemoteFX servers do not require that the connectionType field of the Client Core Data ([MS-RDPBCGR] section 2.2.1.3.2) be set to CONNECTION_TYPE_LAN (0x06).

https://msdn.microsoft.com/en-us/library/ff635250.aspx

**Comment by mailinglists35** [comment]
I am experiencing this on recent versions:
xorgxrdp-0.2.8-1.el7.x86_64
xrdp-0.9.8-1.el7.x86_64

lag is big enough to become a daily annoyance.

any tips to adjust the performance?

**Comment by mailinglists35** [comment]
btw I don't have any `rdpDeferredUpdateCallback` messages in log.
