### ISSUE TITLE
gpg key used to sign the releases not found on key servers

### ISSUE THREAD

**Issue by FelixZhang** [neutrinolabs/xorgxrdp#97]
Hi dear @metalefty . While trying to package xorgxrdp for openSUSE, I found myself unable to verify with the gpg key you used to sign the tarball because the key is not found on the default key server (keys.gnupg.net). Would you please share your key on the key server, or direct me if it's already uploaded elsewhere? Thank you.

**Comment by metalefty** [comment]
Sorry, I forgot to upload the key. I've uploaded my key to pgp.mit.edu. It it OK to you?

**Comment by FelixZhang** [comment]
Thank you very much. That is really helpful. Closing this issue.
